<a href="https://colab.research.google.com/github/AnshumanDec2K/ML_Model_implementation/blob/main/svm_model1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook contains implementation of "SVM"

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn import svm

In [2]:
letters_df = pd.read_csv("/content/letterdata.csv")

In [3]:
letters_df['letter'].value_counts()

U    813
D    805
P    803
T    796
M    792
A    789
X    787
Y    786
N    783
Q    783
F    775
G    773
E    768
B    766
V    764
L    761
R    758
I    755
O    753
W    752
S    748
J    747
K    739
C    736
H    734
Z    734
Name: letter, dtype: int64

In [4]:
letters_df.head(10)

  letter  xbox  ybox  width  height  ...  xy2bar  xedge  xedgey  yedge  yedgex
0      T     2     8      3       5  ...       8      0       8      0       8
1      I     5    12      3       7  ...       9      2       8      4      10
2      D     4    11      6       8  ...       7      3       7      3       9
3      N     7    11      6       6  ...      10      6      10      2       8
4      G     2     1      3       1  ...       9      1       7      5      10
5      S     4    11      5       8  ...       6      0       8      9       7
6      B     4     2      5       4  ...       6      2       8      7      10
7      A     1     1      3       2  ...       8      1       6      2       7
8      J     2     2      4       4  ...       8      1       6      1       7
9      M    11    15     13       9  ...       9      8       1      1       8

[10 rows x 17 columns]

In [5]:
clf = svm.SVC(gamma=0.025, C=10)    
#clf = svm.SVC()

In [6]:
X,y = np.array(letters_df)[ :, 1:16], np.array(letters_df.letter)[:]

In [7]:
X.shape

(20000, 15)

In [8]:
y.shape

(20000,)

In [9]:
y

array(['T', 'I', 'D', ..., 'T', 'S', 'A'], dtype=object)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [11]:
clf.fit(X_train , y_train)

SVC(C=10, gamma=0.025)

In [12]:
clf.score(X_test, y_test)

0.9658333333333333

In [13]:
y_pred = clf.predict(X_test)
pd.crosstab(y_test, y_pred)

col_0    A    B    C    D    E    F    G  ...    T    U    V    W    X    Y    Z
row_0                                     ...
A      232    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
B        0  233    0    1    1    0    0  ...    0    0    1    0    0    0    0
C        0    0  224    0    1    0    0  ...    0    0    0    0    0    0    0
D        0    1    0  222    0    1    1  ...    0    0    0    0    0    0    0
E        0    0    0    0  210    0    0  ...    0    0    0    0    0    0    2
F        0    0    0    0    1  212    0  ...    0    0    1    0    0    0    0
G        0    1    2    0    7    0  214  ...    0    0    1    2    0    0    0
H        0    1    0    6    0    0    1  ...    0    2    0    0    0    0    0
I        0    0    0    0    0    3    0  ...    0    0    0    0    1    0    0
J        0    0    0    0    0    0    1  ...    0    0    0    0    0    0    0
K        0    2    0    2    0    0    0  ...    0    0    0    0    1    0    0
L        0    1    0    0    0    0    0  ...    0    1    0    0    0    0    0
M        0    3    0    0    0    0    1  ...    0    1    0    1    0    0    0
N        0    1    0    6    0    0    0  ...    0    0    3    0    0    0    0
O        0    0    1    4    0    0    0  ...    0    0    0    0    0    0    0
P        0    1    0    1    0   13    0  ...    0    0    0    0    0    3    0
Q        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    1
R        0    5    0    2    1    0    0  ...    0    0    0    0    0    0    0
S        0    0    0    0    1    0    0  ...    0    0    0    0    0    0    1
T        0    0    0    0    4    0    0  ...  247    0    0    0    0    0    0
U        0    0    1    0    0    0    0  ...    0  238    0    0    0    0    0
V        0    5    0    0    0    1    0  ...    0    0  211    0    0    0    0
W        0    0    0    0    0    0    0  ...    0    0    0  227    0    0    0
X        0    1    0    2    0    0    0  ...    0    0    0    0  233    0    0
Y        0    0    0    0    0    0    0  ...    1    2    0    0    1  250    0
Z        0    0    0    0    1    0    0  ...    0    0    0    0    0    0  233

[26 rows x 26 columns]